---
name: CPANPLUS-Dist-Arch
version: 0.15
author:
  - 'Justin Davis <jrcd83@gmail.com>'
abstract: CPANPLUS backend for building Archlinux pacman packages
license: perl
resources:
  repository: http://github.com/juster/perl-cpanplus-dist-arch
requires:
  CPANPLUS: 0
  Carp: 0
  Digest::MD5: 0
  DynaLoader: 0
  File::Copy: 0
  File::Path: 0
  File::Spec::Functions: 0
  File::stat: 0
  Getopt::Long: 0
  IPC::Cmd: 0
  Module::CoreList: 0
  Pod::Select: 0
  Pod::Usage: 0
build_requires:
  Net::Ping: 0
  Test::More: 0
provides:
  CPANPLUS::Dist::Arch:
    file: lib/CPANPLUS/Dist/Arch.pm
    version: 0.15
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
